image: node0.10

script:
  - npm -s install -g grunt-cli bower
  - npm -s install
  - bower install
  - grunt build

notify:

  slack:
    team: iteamsolutions
    channel: #dev
    username: drone.io
    token: 8CucDNnAVELD0BBEErMnhobE
    on_started: true
    on_failure: true
    on_success: true

publish:
  s3:
    acl: public-read
    region: eu-west-1
    bucket: dashboard.iteam.se
    access_key: {{AWS_ACCESS_KEY_ID}}
    secret_key: {{AWS_SECRET_ACCESS_KEY}}
    source: dist/**
    target: /
