image: node0.10
cache:
  - /tmp/npm

script:
  - mkdir -p /tmp/npm
  - sudo chown -R ubuntu:ubuntu /tmp/npm
  - npm config set cache /tmp/npm
  - npm -s install
  - npm -s install -g grunt-cli docpad bower
  - bower install
  - grunt build

notify:

  slack:
    team: iteamsolutions
    channel: #dev
    username: drone.io
    token: 8CucDNnAVELD0BBEErMnhobE
    on_started: true
    on_failure: true
    on_success: true

publish:
  s3:
    acl: public-read
    region: eu-west-1
    bucket: dashboard.iteam.se
    access_key: {{AWS_ACCESS_KEY_ID}}
    secret_key: {{AWS_SECRET_ACCESS_KEY}}
    source: /dist/
    target: latest/
